### ISSUE TITLE
!tar issue 

### ISSUE THREAD

**Issue by IonWolf0** [MauryaRitesh/Facial-Expression-Detection-V2#2]
when i run it :
#Unzipping the file
!tar -xf /content/drive/my-drive/fer2013.tar.gz
tar: /content/drive/my-drive/fer2013.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
--------------------
so any help

**Comment by IonWolf0** [comment]
i found it >> just add double quotation -----> !tar -xf "/content/drive/my-drive/fer2013.tar.gz"
that;s all :)

**Comment by priyaganaboor** [comment]
I am not able to access it.
